version: '3.3'

networks:
  digital-money:

services:
  db:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: digital_money
    ports:
      - "3306:3306"
    networks:
      - digital-money


  eureka-server:
    build: eureka-server/
    ports:
      - '8761:8761'
    restart: always
    networks:
      - digital-money

  gateway:
    build: gateway/
    ports:
      - '3500:3500'
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka
      PORT: 3500
      HOSTNAME: gateway
    depends_on:
      - eureka-server
    restart: always
    networks:
      - digital-money

  user-service:
    build: user-service/
    ports:
      - '8082:8080'
    environment:
      PORT_MS: 8080
      EUREKA_URL: http://eureka-server:8761/eureka
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: rootpassword
      MYSQL_HOST_URL: jdbc:mysql://db:3306/digital_money
      HOSTNAME: user-service
    depends_on:
      - eureka-server
      - db
    restart: always
    networks:
      - digital-money

  account-service:
    build: account-service/
    ports:
      - '8083:8080'
    environment:
      PORT_MS: 8080
      EUREKA_URL: http://eureka-server:8761/eureka
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: rootpassword
      MYSQL_HOST_URL: jdbc:mysql://db:3306/digital_money
      HOSTNAME: account-service
    depends_on:
      - eureka-server
      - db
    restart: always
    networks:
      - digital-money

  auth-service:
    build: auth-service/
    ports:
      - '8081:8080'
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka
      HOSTNAME: auth-service
    depends_on:
      - eureka-server
    restart: always
    networks:
      - digital-money

  dp-backend:
    build: dp-backend/
    ports:
      - '3000:3000'
    environment:
      REACT_APP_API_URL: http://gateway:3500
    depends_on:
      - gateway
    restart: always
    networks:
      - digital-money
