server:
  port: ${PORT:3500}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka}
  instance:
    prefer-ip-address: false
    hostname: ${HOSTNAME:gateway}
