server:
  port: ${PORT:3500}
eureka:
  client:
    service-url:
      defaultZone: http://18.208.207.210/eureka
  instance:
    preferIpAddress: true
    ip-address: 44.200.199.93
    hostname: localhost
