server:
  port: ${PORT:8082}

spring:
  application:
    name: user-service
  config:
    import: optional:env.properties

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_HOST_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql.BasicBinder: trace

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
