server:
  port: ${PORT:8083}

spring:
  application:
    name: account-service
  config:
    import: optional:env.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_HOST_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  properties:
    hibernate:
      format_sql: false

logging:
  level:
    org:
      hibernate:
        SQL: debug

  # Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka}
  instance:
    prefer-ip-address: false
    hostname: ${HOSTNAME:account-service}
